FROM node:20.11.0

WORKDIR /code
COPY ./ ./


## Add the wait script to the image

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN npm install

EXPOSE 4000

CMD [ "node", "local.js" ]
